### ISSUE TITLE
My contribution to your project.

### ISSUE THREAD

**Issue by Hamzeto938** [Master-Console/Master-Browser_#1]
My name is Hamza Yaro  and i am a copywriter, i will love to contribute to your project by writing a FAQ, an About Us and Contact us as i believe this will greatly help your project. I will love to hear your response. Thanks.

**Comment by Yet-Zio** [comment]
Hello Hamza Yaro! Im Yet Zio, the owner of Master-Console_ Inc. As based on your contribution as you said an FAQ Note will be great though but we have recently added the help section in the post on our blog but not in Github. You could help us make a good and decent FAQ note. Your contributions will 
be highly appreciated and will be noted down in the credits.

Come down to our live chat [here](https://tawk.to/chat/593cf9f4b3d02e11ecc6941c/default/?$_tawk_popout=true) to know what all to include before you make an FAQ notice.
Thanks :+1:

**Comment by Yet-Zio** [comment]
No response from user yet.
